### ISSUE TITLE
Are PTMs supported?

### ISSUE THREAD

**Issue by pwilmart** [bittremieux/spectrum_utils#1]
Hi Wout,
Are PTMs supported? I have some (variable) phospho (static) TMT peptides (also with variable Met oxidation and static C+57) to plot for an MCP submission. Thanks and Happy Holidays!
-Phil

**Comment by bittremieux** [comment]
At the moment PTMs aren't supported yet, only non-modified amino acid masses are annotated currently. Modification-awareness is one of the features I want to add for the 0.1 release. Hopefully I'll have some time next week to have a look at it.

In the mean time you can still plot an annotated spectrum for a modified peptide if you provide the peak annotations yourself, although that's less convenient of course.
