### ISSUE TITLE
More detailed document and examples

### ISSUE THREAD

**Issue by hcji** [bittremieux/spectrum_utils#12]
Hi,

Thanks for your great works, but can you give more examples to show the functions of your package? or could you please provide a demo mgf file?

Best wishes,
Ji

**Comment by bittremieux** [comment]
Hi Ji, full code examples are available in the [documentation](https://spectrum-utils.readthedocs.io/en/latest/).

Spectrum IO is not a part of spectrum_utils directly, I typically use [Pyteomics](https://pyteomics.readthedocs.io/en/latest/) for easy reading of common mass spectrometry file formats. The small MGF file used in the documentation code examples is available [here](https://github.com/bittremieux/spectrum_utils/blob/master/docs/spectra.mgf).
