### ISSUE TITLE
Suggestion to make RDkit dependency optional

### ISSUE THREAD

**Issue by RalfG** [bittremieux/spectrum_utils#14]
Hi Wout, 

I recently added spectrum_utils plotting to MS²PIP (works great, thanks!). When running tests in GitHub Actions, I ran into the issue that RDKit is not installed using pip. Since RDKit is only used for molecule drawing, would you agree to make RDKit an optional dependency?

I would propose to put the rdkit imports in a try/except statement, and output a warning if the import fails. E.g. replace

https://github.com/bittremieux/spectrum_utils/blob/842de8bc5b042ee6e2edbf668e8a4407ddfe7cf8/spectrum_utils/plot.py#L9-L10

with

```python
try:
    from rdkit import Chem
    from rdkit.Chem import Draw
except ImportError:
    warnings.warn("RDKit could not be imported. Some spectrum_utils functionality related to molecule drawing might lead to a NameError.", category=ImportWarning)
```

If you agree, I can open a PR.

**Comment by bittremieux** [comment]
RDKit has been removed as a dependency. You can get spectrum_utils v0.3.5 from PyPI now, and from bioconda hopefully asap.

**Comment by RalfG** [comment]
Thanks!
