### ISSUE TITLE
TMT tags

### ISSUE THREAD

**Issue by rsalz** [bittremieux/spectrum_utils#15]
Hi I checked the documentation but couldn't find information on how to add an N-term addition such as a TMT tag. TIA!

**Comment by RalfG** [comment]
Hi @rsalz,

Should be possible like this:
```python
peptide = 'DLTDYLMK'
modifications = {"N-term": 229.162932, 7: 229.162932}

spectrum = sus.spectrum.MsmsSpectrum(
    identifier, precursor_mz, precursor_charge, mz, intensity,
    peptide=peptide, modifications=modifications)
spectrum.annotate_peptide_fragments(10, "ppm", ion_types='aby')
```

See https://spectrum-utils.readthedocs.io/en/latest/processing.html#variable-modifications

**Comment by bittremieux** [comment]
Thank you for jumping in Ralf. That's indeed the correct way to set N-terminal modifications. This is also described in the [API documentation of the `MsmsSpectrum` class](https://spectrum-utils.readthedocs.io/en/latest/api.html#spectrum_utils.spectrum.MsmsSpectrum):

```
modifications (Optional[Dict[Union[int, str], float]], optional) – Mapping of modification positions and mass differences. Valid positions are any amino acid index in the peptide (0-based), ‘N-term’, and ‘C-term’.
```

Don't hesitate to reach out if you have any more issues @rsalz.
