### ISSUE TITLE
Support for 0 mass X amino acids in annotation to enable gapped masses 

### ISSUE THREAD

**Issue by mwang87** [bittremieux/spectrum_utils#19]
This might be subsumed into https://github.com/bittremieux/spectrum_utils/issues/18 as that should be part of the spec. 

Currently, as a user, I fake this by replacing all X's with G and modify the gapped mass value as a faked PTM on the G.

**Comment by bittremieux** [comment]
Fixed in 1d95ff8 and preceding commits.
