### ISSUE TITLE
annotate_molecule_fragment adds SMILES string instead of the structure

### ISSUE THREAD

**Issue by roman-bushuiev** [bittremieux/spectrum_utils#23]
Hi, I would like to annotate a peak with structure as is shown in Figure 1.B in the paper but I am getting its SMILES string instead of the structure:
<img src="https://user-images.githubusercontent.com/37666912/129444038-e63367b4-6ec6-41e7-9776-92a659179553.png" height="500">
I am using the following code:
``` python
spectrum = sus.MsmsSpectrum(usi, precursor_mz, charge, mzs, intensities)\
           .annotate_molecule_fragment(precursor_smiles, precursor_mz, charge, 5, 'ppm')
spectrum_plot = sup.spectrum(spectrum)
```
Maybe it is the wrong way to do it, but I couldn't find an example or figure it out in the documentation.
Thanks!

**Comment by bittremieux** [comment]
Hi Roman, unfortunately structure plotting functionality has been removed in the current version of spectrum_utils.

This functionality used [RDKit](https://www.rdkit.org/) for drawing the molecule. However, unfortunately RDKit is not trivial to install without a package manager such as conda. As this functionality was not used very often, whereas multiple people encountered installation issues, structure drawing was removed for the time being.

**Comment by roman-bushuiev** [comment]
Ok, thanks for the information
