### ISSUE TITLE
Update GNPS USI resolver to GNPS2

### ISSUE THREAD

**Issue by bittremieux** [bittremieux/spectrum_utils#52]
The [`GnpsBackend` should use](https://github.com/bittremieux/spectrum_utils/blob/main/spectrum_utils/spectrum.py#L15) `"https://metabolomics-usi.gnps2.org/proxi/v{version}/spectra?usi={usi}"` now.

**Comment by mwang87** [comment]
Yes! Thanks Wout!

**Comment by bittremieux** [comment]
Fixed in 9bcc3f0.
