### ISSUE TITLE
function: noise peak removal

### ISSUE THREAD

**Issue by danyunghsu** [bittremieux/spectrum_utils#53]
Hi Wout,
Spectrum_utils is so powerful that I have completely switched to spectrum visualization using this tool. Spectrum_utils should be able to remove noise peaks, but I only see the function Msmsspectrum.filter_intensity(). I wonder if spectrum_utils can filter the peaks according to the signal to noise ratio? Is there any interest in adding this function?
Danyung

**Comment by bittremieux** [comment]
Hi Danyung, thank you for the kind words. ☺️

Currently indeed the functionality provided to remove "noise" peaks is to filter low-intensity peaks and/or only retain the top-n most intense peaks using `filter_intensity`. Do you have a bit more information about how your S/N filtering would work or a paper where it is described? How would you define signal and noise?
