### ISSUE TITLE
Matplotlib Version

### ISSUE THREAD

**Issue by mwang87** [bittremieux/spectrum_utils#55]
grid_b was deprecated in version >=3.7, causes an error. 

I was able to fix by pinning matplotlib to version 3.6.3

**Comment by bittremieux** [comment]
Can you give a full stack trace? I don't know where in tehe code `grid_b` would be used.

**Comment by mwang87** [comment]
Its weird, its not in your code. Let me try to reproduce it better and get
back to you.
