### ISSUE TITLE
Can't successfully plot an annotated spectrum

### ISSUE THREAD

**Issue by wsnoble** [bittremieux/spectrum_utils#57]
I wrote a script (attached) based on your tutorial example that attempts to plot an annotated spectrum.  The script runs happily, but the spectrum has no annotation in the resulting plot. Can you let me know if I'm doing something wrong here?

![sample](https://github.com/bittremieux/spectrum_utils/assets/22529318/605b0bb9-9c61-4b8e-aaa2-6e3ba219ba78)

The command line was

```
 ../../../bin/annotate_spectrum.py --mgf sample.mgf --scan 13542 --peptide EEEEEEEDGEEEEEEEEEEEEEEEEEEDEEEEEEEEEEEEEEEEEEEEEEEEEE --root sample
```

[sample.mgf.txt](https://github.com/bittremieux/spectrum_utils/files/13302418/sample.mgf.txt)
[annotate_spectrum.py.txt](https://github.com/bittremieux/spectrum_utils/files/13302423/annotate_spectrum.py.txt)

**Comment by bittremieux** [comment]
Your script is fine, there just aren't any matching peaks for that peptide sequence within a 10 ppm fragment tolerance. If you increase the fragment tolerance to some unrealistic value, you'll see that peaks will be annotated.
