### ISSUE TITLE
Annotating modified lysine Immonium NH3 neutral loss

### ISSUE THREAD

**Issue by HijaziHassan** [bittremieux/spectrum_utils#60]
Hello,

Is there an option to annotate specific diagnostic ions (which are Immonium ions losing NH3). For example,  Kacetyl it will be 126.09 m/z?

Thank you. 
Hassan

**Comment by mwang87** [comment]
Yes totally possible, for example in the interactive interface you can see it here:

http://metabolomics-usi.gnps2.org/dashinterface?usi1=mzspec%3AMSV000085444%3AHui_N3_fe%3Ascan%3A500&width=10.0&height=6.0&mz_min=None&mz_max=None&max_intensity=125&annotate_precision=4&annotation_rotation=90&cosine=standard&fragment_mz_tolerance=0.1&grid=True&annotate_peaks=%5B%5B%5D%2C%20%5B%5D%5D

**Comment by mwang87** [comment]
![spectrum](https://github.com/bittremieux/spectrum_utils/assets/96528/0819738f-c3d1-4c8f-86b4-3d095dbd6dc8)

**Comment by HijaziHassan** [comment]
Thank you for this awesome tool.
I am working with an unpublished data so the usi help me now. Actually, I was using the `pa.annotate_spectrum` function with `backend='spectrum_utils'` from `pyteomics` library. There, I did not find any argument that allow me to annotate such kind of fragments. 
Could you please point me at any?

**Comment by bittremieux** [comment]
If you directly use spectrum_utils itself, you can annotate spectra using [`MsmsSpectrum.annotate_proforma`](https://spectrum-utils.readthedocs.io/en/latest/api.html#spectrum_utils.spectrum.MsmsSpectrum.annotate_proforma).

In your case, you'll want to do the following:
- For immonium ions, include "I" in the `ion_types` of `annotate_proforma`.
- For loss of ammonio, include `{"NH3": -17.026549}` as `neutral_losses`. (Or set `neutral_losses=True` to consider several common losses, as described in the API documentation.)
- By default, spectrum_utils will only display annotated peaks for standard b/y ions. See [here](https://spectrum-utils.readthedocs.io/en/latest/plotting.html#peak-annotations) how to customize the spectrum plotting.
