### ISSUE TITLE
fastobo make difficult to use the package outside linux

### ISSUE THREAD

**Issue by ypriverol** [bittremieux/spectrum_utils#70]
@bittremieux the introduction of fastobo as a dependency block the use of the package outside [linux](https://anaconda.org/bioconda/fastobo/files). It probably would be good to remove that dependency and implement a simple parser of obo files.

**Comment by bittremieux** [comment]
Could you give some more information what the problem is? There are cross-platform wheels for fastobo available through PyPI, so you should be able to install it using pip without too many issues.

**Comment by ypriverol** [comment]
I normally use conda for building my environments. But using pip fastobo also gives errors. I have managed to get a Linux machine to build the containers but keep in mind that the dependency is not available in conda for any other platform. 

I will close the issue, for now.

**Comment by bittremieux** [comment]
I haven't had any issues across multiple platforms. But if installation doesn't work, maybe this is something to mention on the fastobo repository instead then?
