### ISSUE TITLE
non-reproducible example + annotate random ion

### ISSUE THREAD

**Issue by HijaziHassan** [bittremieux/spectrum_utils#71]
Hello,
 The example you provided in the documentation is giving an error:
 
 https://spectrum-utils.readthedocs.io/en/latest/annotating.html
 

```
import matplotlib.pyplot as plt
import spectrum_utils.plot as sup
import spectrum_utils.spectrum as sus


# Retrieve the spectrum by its USI.
usi = "mzspec:MSV000082283:f07074:scan:5475"
spectrum = sus.MsmsSpectrum.from_usi(usi)
```
 ```
 ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[30], line 3
      1 # Retrieve the spectrum by its USI.
      2 usi = "mzspec:MSV000082283:f07074:scan:5475"
----> 3 spectrum = sus.MsmsSpectrum.from_usi(usi)

File [c:\Python310\lib\site-packages\spectrum_utils\spectrum.py:345](file:///C:/Python310/lib/site-packages/spectrum_utils/spectrum.py:345), in MsmsSpectrum.from_usi(cls, usi, backend, **kwargs)
    343             break
    344     else:
--> 345         raise ValueError(
    346             "Unknown precursor m/z from USI. Specify the precursor m/z"
    347             " directly."
    348         )
    349 if "precursor_charge" not in kwargs:
    350     for attr in spectrum_dict["attributes"]:

ValueError: Unknown precursor m/z from USI. Specify the precursor m/z directly.
```
Could you please point me at where the error is coming from? 

Additionally, I want to annotate an ion with specific m/z  that is not among the supported ones,  could you please direct me at the suitable function to use?

**Comment by bittremieux** [comment]
There have been some updates to the USI backends, this is likely related to that. The fixes are currently available in the latest alpha version. Use the following command to upgrade:
```
pip install spectrum_utils==0.5.0a0 --upgrade
```

We need to do a few more tests before creating an official v0.5 release.

> Additionally, I want to annotate an ion with specific m/z that is not among the supported ones, could you please direct me at the suitable function to use?

Annotating a custom peak is currently not super straightforward. You'd have to modify the `annotation` property of an `MsmsSpectrum` directly to assign a custom annotation to the matching peak and then ensure that the plotting function is able to [interpret that annotation](https://spectrum-utils.readthedocs.io/en/latest/plotting.html#peak-annotations).

**Comment by bittremieux** [comment]
Here is an example of how to annotate specific peaks by their m/z value:
```
spec = sus.MsmsSpectrum(...)

peptide = "[+56.02622]-K[+42.0105]SAPATGGVK[+56.02622]K[+56.02622]PHR"
spec.annotate_proforma(peptide, tol_mz, tol_mode)

# Workaround to annotate additional diagnostic ion(s) with a custom mass.
# Note: This can only be done _after_ `annotate_proforma` has been used!
diag_mz = 126.0917
for i, peak_mz in enumerate(spec.mz):
    if abs(md := suu.mass_diff(diag_mz, peak_mz, tol_mode == "Da")) < tol_mz:
        spec.annotation[i] = [
            sufa.FragmentAnnotation(
                ion_type="I",   # Immonium ion.
                charge=1,
                mz_delta=(md, tol_mode),
            )
        ]
```

See the full code [here](https://github.com/user-attachments/files/17587209/diag.txt) (change extension to .py; .txt necessary to add as an attachment). Which gives the following output:
![scan15338](https://github.com/user-attachments/assets/e84fb67c-5415-473c-96e2-667a5b1abbec)

It's not super user-friendly and I should provide a high-level function to do this instead, but you can use this as a temporary workaround.
